### ISSUE TITLE
ctrl-m shortcut not working on OS X

### ISSUE THREAD

**Issue by matklad** [martinkadlec0/The-Switcher#1]
Opera version 22.0
OS X version 10.9.2

Clicking on the extension icon works just fine. 

Also works nice on opera dev on linux :)

**Comment by martinkadlec0** [comment]
In the extension list, below the last extension there should be an "Extension keyboard shortcuts" button. Clicking on it will show you a dialog where you can set your own shortcut. Let me know if setting your own shortcut will fix the problem :)

**Comment by matklad** [comment]
Yes, it worked, thank you! I didn't know it was possible to customise shotrcuts :(
