### ISSUE TITLE
Source code of the latest version

### ISSUE THREAD

**Issue by LukaszWiktor** [martinkadlec0/The-Switcher#2]
Could you push changes in the source code that you made to the latest version? In the [opera addons repository](https://addons.opera.com/en/extensions/details/the-switcher/) is see the version 1.3 whereas here on master there is only 1.0. I'd like to contribute and improve this very useful extension.

**Comment by martinkadlec0** [comment]
Hi, when you upload an extensoin to addons catalog they automaticcly set the version to the right number, so I just leave the manifest be. The commits are all there. Version 1.3 should be b0bd374. There is one newer comit I pushed to github today, which improves loading time of the popup a bit :) Cheers
